name: Publish to NPM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      name:
        required: true
        type: string
      ext:
        required: true
        type: string
      os:
        required: true
        type: string
      cpu:
        required: true
        type: string
    secrets:
      npm_token:
        required: true
      token:
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}.${{ inputs.ext }}
      - name: Extract Binary
        run: |
          # Create directory
          mkdir -p bin
          echo "### Dependency Assets Downloaded" >> $GITHUB_STEP_SUMMARY
          ls -la >> $GITHUB_STEP_SUMMARY
          
          # Extract the binary
          if [[ "${{ inputs.ext }}" == "zip" ]]; then
            7z x ${{ inputs.name }}.${{ inputs.ext }} -obin
          else
            tar -xzf ${{ inputs.name }}.${{ inputs.ext }} -C bin
          fi
      - name: Publish Binary
        run: |

          # Custom package.json
          echo '{"name": "@govcraft/${{ inputs.name }}", "version": "${{ inputs.version }}", "os": ["${{ inputs.os }}"], "cpu": ["${{ inputs.cpu }}"], "author": {"name": "Govcraft", "email": "roland@govcraft.ai"}}' | jq . > package.json
          
          # Publish the package
          npm publish --access public
          
          # Update GitHub summary
          echo "### Published **@govcraft/${{ inputs.name }}** to **NPM**" >> $GITHUB_STEP_SUMMARY
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
